### ISSUE TITLE
Running local flows without GPUs

### ISSUE THREAD

**Issue by hugobowne** [jacopotagliabue/you-dont-need-a-bigger-boat#10]
hi all!

Thank you for these incredible resources :)

how would I run the local flow if I don't have access to any GPUs?

https://github.com/jacopotagliabue/you-dont-need-a-bigger-boat/tree/main/local_flow

**Comment by patrickjohncyh** [comment]
hi @hugobowne! Are you facing any specific challenge when running the local flow w/o GPU? In general, if you set the `EN_BATCH` to 0 i.e. (`EN_BATCH=0`) then it should run locally.

**Comment by hugobowne** [comment]
thanks @patrickjohncyh that worked for me!

May be worth making this option explicit in the docs/README.md

Apologies if it's already there and I missed it
